# Generated by Django 5.2 on 2025-04-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='summery',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expirence',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(default='Not Provided'),
        ),
    ]
