# Generated by Django 5.2 on 2025-04-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
