# Generated by Django 5.2 on 2025-04-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_resume_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
